### ISSUE TITLE
本地运行出错,出错代码如下

### ISSUE THREAD

**Issue by hjaiim** [xuqiang521/nuxt-ssr-demo#9]
求大佬解惑,难道我要再配置es6么?在线等,挺急的

**Comment by hjaiim** [comment]
`
Desktop/nuxt-ssr-demo-dev/node_modules/nuxt/lib/core/middleware/nuxt.js:72
      const policies = this.options.render.csp.policies ? {...this.options.render.csp.policies} : null
                                                           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)`

**Comment by xuqiang521** [comment]
fixed
